# -*- coding: utf-8 -*-
"""image.search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvC28yxIjBJ5Phj-qa2GaMQg23R6ZEka
"""

import pandas as pd
import numpy as np
import requests
from io import BytesIO
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing import image
from sklearn.metrics.pairwise import cosine_similarity

#df = pd.read_csv("/content/drive/MyDrive/datste/preprocessed_dataset_curatiled.csv")
df = pd.read_csv("preprocessed_dataset_curatiled.csv")
# Optional: filter out rows without images
df = df[df['images'].notnull()]

def preprocess_image(img_url):
    try:
        response = requests.get(img_url)
        img = Image.open(BytesIO(response.content)).convert('RGB')
        img = img.resize((224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0)
        return preprocess_input(img_array)
    except:
        return None

model = ResNet50(weights='imagenet', include_top=False, pooling='avg')

def extract_features(img_url):
    img = preprocess_image(img_url)
    if img is None:
        return None
    features = model.predict(img, verbose=0)
    return features.flatten()

import os

FEATURES_FILE = "image_features.npy"
INDICES_FILE = "valid_indices.npy"

if os.path.exists(FEATURES_FILE) and os.path.exists(INDICES_FILE):
    print("Loading cached features...")
    image_features = np.load(FEATURES_FILE)
    valid_indices = np.load(INDICES_FILE)
    df = df.iloc[valid_indices].reset_index(drop=True)
else:
    print("Extracting features, this may take a while...")
    image_features = []
    valid_indices = []
    for idx, row in tqdm(df.iterrows(), total=len(df)):
        img_urls = eval(row['images'])  # Ensure it's a list of URLs
        if img_urls:
            features = extract_features(img_urls[0])
            if features is not None:
                image_features.append(features)
                valid_indices.append(idx)
    # Filter the original dataframe to only include valid images
    df = df.iloc[valid_indices].reset_index(drop=True)
    image_features = np.array(image_features)
    np.save(FEATURES_FILE, image_features)
    np.save(INDICES_FILE, valid_indices)
    print("Features cached for future runs.")

def recommend_similar_images(input_image_path, top_k=5):
    # Load and extract features for input image
    img = Image.open(input_image_path).convert('RGB').resize((224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)
    query_feature = model.predict(img_array, verbose=0).flatten()

    # Compute cosine similarity
    similarities = cosine_similarity([query_feature], image_features)[0]
    top_indices = similarities.argsort()[-top_k:][::-1]

    results = []
    for idx in top_indices:
        title = df.iloc[idx]['title']
        url = df.iloc[idx]['url']
        img_urls = eval(df.iloc[idx]['images'])
        image_url = img_urls[0] if img_urls else None
        results.append({
            'title': title,
            'url': url,
            'image_url': image_url
        })
    return results

# Flask/REST API wrapper

def get_similar_images_api(uploaded_image_path, top_k=5):
    """
    Given a local image path, return a list of dicts with similar images.
    """
    return recommend_similar_images(uploaded_image_path, top_k=top_k)

def display_image(img_url):
    try:
        response = requests.get(img_url)
        img = Image.open(BytesIO(response.content))
        plt.imshow(img)
        plt.axis('off')
        plt.show()
    except:
        print("Could not load image.")

# Provide path to your test image (upload it or give path)
#![images](images.jpeg)
#image_path = "images.jpeg"
# recommend_similar_images("/content/drive/MyDrive/datste/images.jpeg", top_k=5)

